### ISSUE TITLE
Clarify the "Hosting Discussion" Section

### ISSUE THREAD

**Issue by connor4312** [minecraftforum/rules-archive#183]
The hosting discussion section is a great idea, but (seeing as about a third of the topics on there are locked, and another third is moved) I think some clarification on what to _do_ on there would be good, not just what to _not do_.

**Comment by LordRalex** [comment]
Do you have any suggestions for this? Part of me just feels like no one read the rules, because that is where a lot of the topics are coming from.

**Comment by connor4312** [comment]
Well, from what I can see on the forum at the moment, Hosting Discussion mainly consists of:
- Requests for staff or aid
- Guides relating to the hosting of servers
- Websites relating to or assisting with server hosting
- Questions about hardware or service providers related to dedicated hosting

Perhaps mention those as examples of topics which belong in the Hosting Discussion section. That might help focus people on what actually goes there.

Assuming people actually read the rules. *rolls eyes*

**Comment by LordRalex** [comment]
So just going over what can go there as well as what cannot. Seems reasonable, considering the only thing we ever do now is a bunch of do not's.

I'll look into this and work up some changes to help make it clearer.
