### ISSUE TITLE
Looking for rules / Minecraft Server Hosting -- "refer to this topic"

### ISSUE THREAD

**Issue by shrink** [minecraftforum/rules-archive#9]
The style guide explains that external links are not supposed to be used unless absolutely necessary, under both "Looking for" and "Minecraft server hosting" links are used to further explain the rules.

These need to be removed and the rules added to the rules document.

**Comment by shrink** [comment]
http://rules.mcf.li/#servers:looking_for  
http://rules.mcf.li/#servers:minecraft_server_hosting

**Comment by 8bitben** [comment]
Issue addressed in [pull #10](https://github.com/minecraftforum/rules/pull/10)
