### ISSUE TITLE
Replace 'No embedded video (informal)' infraction

### ISSUE THREAD

**Issue by Kavalist** [minecraftforum/rules-archive#97]
Since this infraction has been tossed under the bus with the new auto-embedding, there hasn't much been an issue with no embedded video but people simply posting their youtuble channel. And when I say issue, I mean there can be about one of these threads every few hours. So, I propose an updated infraction (informal) to replace the old one. Possibly:

Channel linking (informal)

The Video and Let's Play subforums are for posting actual videos, not linking to YouTube channels or playlists. If you wish to make a post to discuss videos, please post a video url in the topic so there is content to discuss.

**Comment by JefeCC** [comment]
You can add the rule yourself

**Comment by Kavalist** [comment]
Its not a rule addition, its an infraction edit

**Comment by DanielleStarr** [comment]
Never thought of that, thanks Kaval I'll get onto Puyo

Aaaaaaaaaaaand done
